development:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_production
  pool: 5
